package com.demo.common.model;

import com.demo.common.model.base.BaseBlog;

/**
 * Generated by JFinal.
 */
/**
 * @author Created by zhaosy<a href="mailto:zhaosy@chsi.com.cn">Zhao Shiying</a>
 *
 * @version   Created in 2017/10/16 12:53
 * 
 */

@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
	public static final Blog dao = new Blog().dao();
}
